name: uni_platform
description: "Substitutes the Platform class, ensuring works across all platforms."
version: 0.1.3
homepage: https://github.com/leanflutter/uni_platform

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1
