name: uni_platform
description: "Replaces the Platform class and works on any platform."
version: 0.1.0
homepage: https://github.com/leanflutter/uni_platform

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
