name: lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"
          channel: "stable"
      - run: flutter analyze --fatal-infos

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"
          channel: "stable"
      - run: dart format . --fix --set-exit-if-changed
